// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: Header/locale.proto

package Header

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Locale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CLocale       *Locale_LocaleIds      `protobuf:"bytes,1,opt,name=cLocale" json:"cLocale,omitempty"`
	SLocale       *Locale_LocaleIds      `protobuf:"bytes,2,opt,name=sLocale" json:"sLocale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locale) Reset() {
	*x = Locale{}
	mi := &file_Header_locale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale) ProtoMessage() {}

func (x *Locale) ProtoReflect() protoreflect.Message {
	mi := &file_Header_locale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale.ProtoReflect.Descriptor instead.
func (*Locale) Descriptor() ([]byte, []int) {
	return file_Header_locale_proto_rawDescGZIP(), []int{0}
}

func (x *Locale) GetCLocale() *Locale_LocaleIds {
	if x != nil {
		return x.CLocale
	}
	return nil
}

func (x *Locale) GetSLocale() *Locale_LocaleIds {
	if x != nil {
		return x.SLocale
	}
	return nil
}

type Locale_LocaleIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      *string                `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
	Script        *string                `protobuf:"bytes,2,opt,name=script" json:"script,omitempty"`
	Region        *string                `protobuf:"bytes,3,opt,name=region" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locale_LocaleIds) Reset() {
	*x = Locale_LocaleIds{}
	mi := &file_Header_locale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locale_LocaleIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locale_LocaleIds) ProtoMessage() {}

func (x *Locale_LocaleIds) ProtoReflect() protoreflect.Message {
	mi := &file_Header_locale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locale_LocaleIds.ProtoReflect.Descriptor instead.
func (*Locale_LocaleIds) Descriptor() ([]byte, []int) {
	return file_Header_locale_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Locale_LocaleIds) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *Locale_LocaleIds) GetScript() string {
	if x != nil && x.Script != nil {
		return *x.Script
	}
	return ""
}

func (x *Locale_LocaleIds) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

var File_Header_locale_proto protoreflect.FileDescriptor

const file_Header_locale_proto_rawDesc = "" +
	"\n" +
	"\x13Header/locale.proto\"\xbb\x01\n" +
	"\x06Locale\x12+\n" +
	"\acLocale\x18\x01 \x01(\v2\x11.Locale.LocaleIdsR\acLocale\x12+\n" +
	"\asLocale\x18\x02 \x01(\v2\x11.Locale.LocaleIdsR\asLocale\x1aW\n" +
	"\tLocaleIds\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06regionBUZ<github.com/nilaonai/bbdown-go/internal/core/api/proto/Header\xaa\x02\x14BBDown.Core.Protobuf"

var (
	file_Header_locale_proto_rawDescOnce sync.Once
	file_Header_locale_proto_rawDescData []byte
)

func file_Header_locale_proto_rawDescGZIP() []byte {
	file_Header_locale_proto_rawDescOnce.Do(func() {
		file_Header_locale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Header_locale_proto_rawDesc), len(file_Header_locale_proto_rawDesc)))
	})
	return file_Header_locale_proto_rawDescData
}

var file_Header_locale_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Header_locale_proto_goTypes = []any{
	(*Locale)(nil),           // 0: Locale
	(*Locale_LocaleIds)(nil), // 1: Locale.LocaleIds
}
var file_Header_locale_proto_depIdxs = []int32{
	1, // 0: Locale.cLocale:type_name -> Locale.LocaleIds
	1, // 1: Locale.sLocale:type_name -> Locale.LocaleIds
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Header_locale_proto_init() }
func file_Header_locale_proto_init() {
	if File_Header_locale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Header_locale_proto_rawDesc), len(file_Header_locale_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Header_locale_proto_goTypes,
		DependencyIndexes: file_Header_locale_proto_depIdxs,
		MessageInfos:      file_Header_locale_proto_msgTypes,
	}.Build()
	File_Header_locale_proto = out.File
	file_Header_locale_proto_goTypes = nil
	file_Header_locale_proto_depIdxs = nil
}
